# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hydeweb}
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rico Sta. Cruz", "Sinefunc, Inc."]
  s.date = %q{2010-11-24}
  s.default_executable = %q{hyde}
  s.description = %q{Website preprocessor}
  s.email = %q{rico@sinefunc.com}
  s.executables = ["hyde"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".yardopts",
    "AUTHORS",
    "CHANGELOG",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/hyde",
    "data/new_site/.gitignore",
    "data/new_site/README.md",
    "data/new_site/hyde.conf",
    "data/new_site/layouts/default.haml",
    "data/new_site/site/index.html.haml",
    "data/pages/404.html",
    "hydeweb.gemspec",
    "lib/hyde.rb",
    "lib/hyde/clicommand.rb",
    "lib/hyde/clicommands.rb",
    "lib/hyde/helpers.rb",
    "lib/hyde/layout.rb",
    "lib/hyde/meta.rb",
    "lib/hyde/ostruct.rb",
    "lib/hyde/page.rb",
    "lib/hyde/page_factory.rb",
    "lib/hyde/partial.rb",
    "lib/hyde/project.rb",
    "lib/hyde/renderer.rb",
    "lib/hyde/renderers.rb",
    "lib/hyde/sinatra/init.rb",
    "lib/hyde/utils.rb",
    "lib/hyde_misc/console.rb",
    "manual/Extending/ExtendingHyde.md",
    "manual/Hyde.md",
    "manual/Introduction/Configuration.md",
    "manual/Introduction/GettingStarted.md",
    "manual/Introduction/Installation.md",
    "manual/Introduction/Layouts.md",
    "manual/Introduction/Metadata.md",
    "manual/Introduction/Partials.md",
    "manual/Introduction/TemplateLanguages.md",
    "manual/Tips/Tips.md",
    "test/fixtures/content_for/_config.yml",
    "test/fixtures/content_for/layouts/cf-args.haml",
    "test/fixtures/content_for/layouts/cf.haml",
    "test/fixtures/content_for/layouts/default.haml",
    "test/fixtures/content_for/layouts/shared/test.haml",
    "test/fixtures/content_for/site/cf-args-default.haml",
    "test/fixtures/content_for/site/cf-args.haml",
    "test/fixtures/content_for/site/cf.haml",
    "test/fixtures/content_for/site/cf2.haml",
    "test/fixtures/content_for/site/default.html.haml",
    "test/fixtures/content_for/site/index.html.haml",
    "test/fixtures/content_for/site/var.html.haml",
    "test/fixtures/content_for/www_control/cf-args-default.html",
    "test/fixtures/content_for/www_control/cf-args.html",
    "test/fixtures/content_for/www_control/cf.html",
    "test/fixtures/content_for/www_control/cf2.html",
    "test/fixtures/content_for/www_control/default.html",
    "test/fixtures/content_for/www_control/index.html",
    "test/fixtures/content_for/www_control/var.html",
    "test/fixtures/custom/_config.yml",
    "test/fixtures/custom/extensions/custom/custom.rb",
    "test/fixtures/custom/layouts/default.haml",
    "test/fixtures/custom/layouts/erbtest.erb",
    "test/fixtures/custom/layouts/shared/sidebar.haml",
    "test/fixtures/custom/site/about/index.html",
    "test/fixtures/custom/site/assets/common.css.less",
    "test/fixtures/custom/site/assets/style.css.less",
    "test/fixtures/custom/site/foo.html.haml",
    "test/fixtures/custom/site/index.html.haml",
    "test/fixtures/custom/site/layout_test.html.haml",
    "test/fixtures/custom/site/lol.html.erb",
    "test/fixtures/custom/site/markdown.html.md",
    "test/fixtures/custom/site/yes.html",
    "test/fixtures/custom/www_control/about/index.html",
    "test/fixtures/custom/www_control/assets/common.css",
    "test/fixtures/custom/www_control/assets/style.css",
    "test/fixtures/custom/www_control/foo.html",
    "test/fixtures/custom/www_control/index.html",
    "test/fixtures/custom/www_control/layout_test.html",
    "test/fixtures/custom/www_control/lol.html",
    "test/fixtures/custom/www_control/markdown.html",
    "test/fixtures/custom/www_control/yes.html",
    "test/fixtures/default/_config.yml",
    "test/fixtures/default/extensions/custom/custom.rb",
    "test/fixtures/default/layouts/default.haml",
    "test/fixtures/default/site/about/index.html",
    "test/fixtures/default/site/foo.html.haml",
    "test/fixtures/default/site/index.html.haml",
    "test/fixtures/default/site/layout_test.html.haml",
    "test/fixtures/default/site/yes.html",
    "test/fixtures/default/www_control/about/index.html",
    "test/fixtures/default/www_control/foo.html",
    "test/fixtures/default/www_control/index.html",
    "test/fixtures/default/www_control/layout_test.html",
    "test/fixtures/default/www_control/yes.html",
    "test/helper.rb",
    "test/test_all_fixtures.rb",
    "test/test_build.rb",
    "test/test_hyde.rb",
    "test/test_page.rb",
    "test/test_utils.rb"
  ]
  s.homepage = %q{http://github.com/sinefunc/hyde}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Website preprocessor}
  s.test_files = [
    "test/fixtures/custom/extensions/custom/custom.rb",
    "test/fixtures/default/extensions/custom/custom.rb",
    "test/helper.rb",
    "test/test_all_fixtures.rb",
    "test/test_build.rb",
    "test/test_hyde.rb",
    "test/test_page.rb",
    "test/test_utils.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<less>, [">= 1.2.21"])
      s.add_runtime_dependency(%q<haml>, [">= 2.2.20"])
    else
      s.add_dependency(%q<sinatra>, [">= 1.0.0"])
      s.add_dependency(%q<less>, [">= 1.2.21"])
      s.add_dependency(%q<haml>, [">= 2.2.20"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 1.0.0"])
    s.add_dependency(%q<less>, [">= 1.2.21"])
    s.add_dependency(%q<haml>, [">= 2.2.20"])
  end
end

