# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hydeweb}
  s.version = "0.0.1.pre1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rico Sta. Cruz", "Sinefunc, Inc."]
  s.date = %q{2010-04-27}
  s.default_executable = %q{hyde}
  s.description = %q{Website preprocessor}
  s.email = %q{rico@sinefunc.com}
  s.executables = ["hyde"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     ".yardopts",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/hyde",
     "hyde.gemspec",
     "hydegen.gemspec",
     "lib/hyde.rb",
     "lib/hyde/init.rb",
     "lib/hyde/layout.rb",
     "lib/hyde/ostruct.rb",
     "lib/hyde/page.rb",
     "lib/hyde/project.rb",
     "lib/hyde/renderer.rb",
     "lib/hyde/renderers.rb",
     "lib/hyde/utils.rb",
     "test/fixtures/default/_config.yml",
     "test/fixtures/default/_layouts/default.haml",
     "test/fixtures/default/about/index.html",
     "test/fixtures/default/foo.html.haml",
     "test/fixtures/default/hyde",
     "test/fixtures/default/index.html.haml",
     "test/fixtures/default/layout_test.html.haml",
     "test/fixtures/default/yes.html",
     "test/helper.rb",
     "test/test_hyde.rb"
  ]
  s.homepage = %q{http://github.com/sinefunc/hyde}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Website preprocessor}
  s.test_files = [
    "test/helper.rb",
     "test/test_hyde.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<less>, [">= 1.2.21"])
      s.add_runtime_dependency(%q<haml>, [">= 2.2.20"])
    else
      s.add_dependency(%q<sinatra>, [">= 1.0.0"])
      s.add_dependency(%q<less>, [">= 1.2.21"])
      s.add_dependency(%q<haml>, [">= 2.2.20"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 1.0.0"])
    s.add_dependency(%q<less>, [">= 1.2.21"])
    s.add_dependency(%q<haml>, [">= 2.2.20"])
  end
end

